apiVersion: v1
kind: Pod
metadata:
  name: helm
  annotations:
    jenkins/label: helm
  labels:
    app.kubernetes.io/name: jenkins
    jenkins/label: helm
spec:
  containers:
    - name: helm
      environment:
        - name: "JENKINS_TUNNEL"
          value: "jenkins-agent.jenkins.svc.cluster.local:50000"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
        - name: "JENKINS_URL"
          value: "http://jenkins.jenkins.svc.cluster.local:80/"
      image: ghcr.io/edwardtheharris/helm-jenkins/helm:0.0.1-05
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: jnlp
      image: jenkins/inbound-agent:latest-jdk25
      environment:
        - name: "JENKINS_TUNNEL"
          value: "jenkins-agent.jenkins.svc.cluster.local:50000"
        - name: "REMOTING_OPTS"
          value: "-noReconnectAfter 1d"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
        - name: "JENKINS_URL"
          value: "http://jenkins.jenkins.svc.cluster.local:80/"
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: docker
      image: docker:1.11
      command: ["cat"]
      environment:
        - name: "JENKINS_TUNNEL"
          value: "jenkins-agent.jenkins.svc.cluster.local:50000"
        - name: "JENKINS_AGENT_NAME"
          value: "helm-helm-jenkins-28-update-deployment-from-thw-12-58jl3--9450s"
        - name: "JENKINS_AGENT_FILE"
          value: "/jenkins-agent/agent.jar"
        - name: "REMOTING_OPTS"
          value: "-noReconnectAfter 1d"
        - name: "JENKINS_NAME"
          value: "helm-helm-jenkins-28-update-deployment-from-thw-12-58jl3--9450s"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
        - name: "JENKINS_URL"
          value: "http://jenkins.jenkins.svc.cluster.local:80/"
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  imagePullSecrets:
    - name: ghcr
  volumes:
    - name: dockersock
      hostPath:
        path: /run/containerd/containerd.sock
