apiVersion: v1
kind: Pod
metadata:
  name: helm
  annotations:
    jenkins/label: helm
  labels:
    app.kubernetes.io/name: jenkins
    jenkins/label: helm
spec:
  containers:
    - name: helm
      command:
        - "/usr/local/bin/jenkins-agent"
      args:
        - "-name"
        - "${computer.name}"
        - "-secret"
        - "${computer.jnlpmac}"
      environment:
        - name: "JENKINS_TUNNEL"
          value: "jenkins-agent.jenkins.svc.cluster.local:50000"
        - name: "JENKINS_URL"
          value: "http://jenkins.jenkins.svc.cluster.local:80/"
      image: ghcr.io/edwardtheharris/helm-jenkins/helm:0.0.1-06
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  imagePullSecrets:
    - name: ghcr
  volumes:
    - name: dockersock
      hostPath:
        path: /run/containerd/containerd.sock
