apiVersion: v1
kind: Pod
metadata:
  name: helm
  annotations:
    jenkins/label: helm
  labels:
    app.kubernetes.io/name: jenkins
    jenkins/label: helm
spec:
  containers:
    - name: helm
      image: ghcr.io/edwardtheharris/helm-jenkins/helm:0.0.1-05
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: jnlp
      image: jenkins/inbound-agent:3355.v388858a_47b_33-3-jdk21
      command:
        - "/bin/sh"
        - "-c"
        - >-
          mkdir -pv jenkins-agent;cp $(command -v jenkins-agent) jenkins-agent/jenkins-agent;cp -R /usr/share/jenkins/ ./jenkins-agent
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: docker
      image: docker:1.11
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  imagePullSecrets:
    - name: ghcr
  volumes:
    - name: dockersock
      hostPath:
        path: /run/containerd/containerd.sock
